name: Update Branches

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  push:
    branches:
      - master # Changed from main to master

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master # Changed from main to master

      - name: Update all branches
        run: |
          git fetch --all
          for branch in $(git branch -r | grep -vE "origin/master$" | sed 's/origin\///'); do
            echo "Creating pull request for branch $branch"
            git checkout -b update-master-$branch origin/$branch
            git merge master --allow-unrelated-histories
            git push origin update-master-$branch
            gh pr create --base $branch --head update-master-$branch --title "Update $branch from master" --body "This PR updates $branch with the latest changes from the master branch."
          done


      - name: Set up GitHub CLI
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'

      - name: Install GitHub CLI
        run: |
          curl -sSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth setup-git
